framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                  max_retries: 0
                  # задержка в милисекундах
                  delay: 1000
                  # делает так, чтобы задержка была дольше перед каждой повторной попыткой
                  # например, задержка в 1 секунду, 2 секунду, 4 секунду
                  multiplier: 2
                  max_delay: 0
                  # переопределить это все сервисом, который
                  # реализует Symfony\Component\Messenger\Retry\RetryStrategyInterface
                  # service: null
             failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
             'App\Message\UploadedFileProcessor': async
             'App\Message\ProductCreator': async

when@test:
  framework:
      messenger:
          failure_transport: failed
          transports:
              # replace with your transport name here (e.g., my_transport: 'in-memory://')
              # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
            async_in_memory: 'in-memory://'
          routing:
            # Route your messages to the transports
            'App\Message\UploadedFileProcessor': async_in_memory
            'App\Message\ProductCreator': async_in_memory
