version: '3.8'

services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: ${APP_DATABASE_NAME}
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_SECRET}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "${APP_DATABASE_PORT}:5432"
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - "9001:9000"
    volumes:
      - .:/var/www/web
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8040:80"
    volumes:
      - .:/var/www/web
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php