services:
  App\Entity\ProductRepositoryRead:
    alias: App\Repository\ProductRepository
    public: true
  App\Entity\ProductRepositoryPersist:
    alias: App\Repository\ProductRepository
    public: true
  App\Entity\CategoryRepositoryPersist:
    alias: App\Repository\CategoryRepository
    public: true
  App\Entity\CategoryRepositoryRead:
    alias: App\Repository\CategoryRepository
    public: true
