services:
  # redefine the alias as it should be while making it public
  App\Entity\ProductRepositoryRead:
    alias: App\Repository\ProductRepository
    public: true
  App\Entity\ProductRepositoryPersist:
    alias: App\Repository\ProductRepository
    public: true
  App\Entity\CategoryRepositoryPersist:
    alias: App\Repository\ProductRepository
    public: true
  App\Entity\CategoryRepositoryRead:
    alias: App\Repository\ProductRepository
    public: true
