parameters:
  public_directory: '%kernel.project_dir%/public'
  test_uploads_directory: '%public_directory%/uploads'
  uploads_directory_to_read: '%kernel.project_dir%/tests/test_uploads'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $uploadPath: '%test_uploads_directory%'
  App\Handler\ProductCreate:
    public: true
  App\Entity\ProductRepositoryRead:
    alias: App\Repository\ProductRepository
    public: true
  App\Entity\ProductRepositoryPersist:
    alias: App\Repository\ProductRepository
    public: true
  App\Entity\CategoryRepositoryPersist:
    alias: App\Repository\CategoryRepository
    public: true
  App\Entity\CategoryRepositoryRead:
    alias: App\Repository\CategoryRepository
    public: true
